services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ticketmaster
      POSTGRES_USER: ticketmaster
      POSTGRES_PASSWORD: ticketmaster
    networks:
      - app_net
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticketmaster -d ticketmaster"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  app1:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ticketmaster
      SPRING_DATASOURCE_USERNAME: ticketmaster
      SPRING_DATASOURCE_PASSWORD: ticketmaster
      SERVER_PORT: 8001
      JAVA_OPTS: -Xms128m -Xmx256m
    networks:
      - app_net
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8001/events >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    cpus: "0.50"
    mem_limit: "512m"

  app2:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ticketmaster
      SPRING_DATASOURCE_USERNAME: ticketmaster
      SPRING_DATASOURCE_PASSWORD: ticketmaster
      SERVER_PORT: 8002
      JAVA_OPTS: -Xms128m -Xmx256m
    networks:
      - app_net
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8002/events >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    cpus: "0.50"
    mem_limit: "512m"

  lb:
    image: nginx:1.27-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_net
    depends_on:
      app1:
        condition: service_healthy
      app2:
        condition: service_healthy

  k6:
    image: grafana/k6:0.50.0
    profiles: ["loadtest"]
    depends_on:
      - lb
    volumes:
      - ./loadtest:/scripts:ro
    entrypoint: ["k6", "run", "/scripts/k6.js"]
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
